name: PR Diff Comment

on:
  workflow_run:
    workflows: ["PR Diff Artifact"]
    types:
      - completed

jobs:
  comment-diff-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Download PR diff artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-diff
          run-id: ${{ github.event.workflow_run.id }}

      - name: Count diff lines
        id: count
        run: |
          lines=$(grep -E '^[+-]' pr-diff.txt | grep -vE '^(\+\+\+|---)' | wc -l)
          echo "lines=$lines" >> $GITHUB_OUTPUT

      - name: Create PR comment with diff line count
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: context.payload.workflow_run.head_branch
            });
            if (pr.data.length > 0) {
              const prNumber = pr.data[0].number;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: `PR diff line count: ${{ steps.count.outputs.lines }}`
              });
            }
